### ISSUE TITLE
Litespeed cache plugin is generating a huge databases

### ISSUE THREAD

**Issue by closte** [litespeedtech/lscache_wp#286] opened 2021-01-12 16:51 UTC
Litespeed cache plugin is saving a ton of data in the database and this just makes us hosting services having a lot of problems.

![litespeed_cssjs](https://user-images.githubusercontent.com/26750475/104343758-a021e600-54fc-11eb-8e0e-e632079b2793.png)

In most cases, this database table is far larger compared to the sum of all other tables, so we, hosting services are having a lot of performance and memory management issues.

Now, imagine if 100+ websites are using the same setting and having a 2+ GB of database content, that's 200GB of database size!

This should be changed in the way the other caching plugins are working.
You are using the database table for some kind of key/value pairs, so you can do the same using files, for example, you can save the hash as a unique file and the file can have JSON content if you need to have a more complex value.

In this case, the database sizes will be far smaller and let the system memory cache the files, so in terms of performance, it will be the same (hope we don't talk about 1ms or nanoseconds).

**Comment by hi-hai** [comment] 2021-01-12 17:28
I believe most of those cases are caused by random string issues. 

We have a todo to check the amount of records, if reached the threshold, will stop new generation or delete old ones.

However, your report gave me another idea. We will totally dropped this table, stored them in folder directly along w/ the css/js files. This is to say, for the file `wp-content/litespeed/cssjs/abced.css`, there will be another file `abced.css.json` so that each time when users purged css while not purge page cache, the css file can still be dynamically generated.

**Comment by closte** [comment] 2021-01-12 18:18
You are querying the database table only by ID, so your use case is **key/value storage**, so if something can be made using MySQL, you can make the same using the filesystem.

Ofc, you may need to change the logic of how you purge the files, cache and so on.

We are recommending the following structure:

Filename: hash
Content: Json (You can include the refer and dateline values into this content)
Performance: It looks like the plugin is just parsing one or maybe a few records, so it doesn't really matter of the hash/storing method.

Just a tip!

**Comment by Tangol** [comment] 2021-04-23 23:32
I'm also waiting for a fix to this, as my hosting has a 4GB database limit, so the plugin is pretty much unusable for me.

Thanks!

**Comment by Tangol** [comment] 2021-05-24 08:52
> I believe most of those cases are caused by random string issues.
> 
> We have a todo to check the amount of records, if reached the threshold, will stop new generation or delete old ones.
> 
> However, your report gave me another idea. We will totally dropped this table, stored them in folder directly along w/ the css/js files. This is to say, for the file `wp-content/litespeed/cssjs/abced.css`, there will be another file `abced.css.json` so that each time when users purged css while not purge page cache, the css file can still be dynamically generated.

@hi-hai any chance of getting this fixed in v4.1?
I consider it a major issue, as no caching plugin should actually touch the database when doing cache work.
It's a blocker for us that have limited hosting resources.

Thanks!

**Comment by hi-hai** [comment] 2021-05-24 12:03
@Tangol 
Have you tried latest dev? It is fixed in v4.0 already.

**Comment by Tangol** [comment] 2021-05-24 12:31
@hi-hai I just did. Looks good, thanks a lot!

**Closed** 2021-05-24 12:31 UTC
